name: Build and Release AHK EXE
# 这文件有点问题  以后有空再说
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  example:
#    name: Example
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Compile with Ahk2Exe
#        uses: cennis91/action-ahk2exe@main
#        id: ahk2exe
#        with:
#          in: GooglePinyin2LoadLua.ahk
#          out: GooglePinyin2LoadLua.exe
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: compiled-binary
#          path: ${{ steps.ahk2exe.outputs.binary }}